### PR TITLE
major refactoring

### PR DESCRIPTION
**Pull request by mjpost**
I don't think you'll want this refactoring, but I am creating a PR so you can see it. I think I've simplified things quite a bit and maybe you can take a thing or two from it.

The major difference is that I was getting tired of managing complex workflows, and realized that ducttape, while awesome, does not make it easy to reason about these complex workflows. It is much easier to have a simpler hypergraph and put complexity *into* steps.

For this reason, the major simplification is that all steps now take both $src_in and $trg_in, and output $src and $trg. The advantage is that there is no more `side` branch variable, and the steps are much simpler and easier to piece together. We can now move from copying raw data, to masking, tokenization, source factor computation, and subword process, all quite easily.

As an extra advantage, it gets ride of the dummy steps again :)

The test path was always different. I have handled this by bundling a model. The model bundle takes raw input and output raw output. This means that the bundle itself has to repeat all the logic. This is a complexity, but it is much simpler, IMO, than trying to factor out this logic in the ducttape graph (where some steps are the same between training and testing, and some are different). The raw output can also be passed directly to sacrebleu.

The "test" plan makes it easy to test: it completes in about 20 minutes, using both sentence piece (with random sampling) and BPE with a few simple source factors.

### CODE REVIEW

**Comment by shuoyangd** [comment]
Thanks, I'll slowly work my way through it :)

I also just realized there is "test" plan in the workflow. Looks like we can just use this for CI!

**Comment by mjpost** [comment]
Yeah, I didn't realize how much we'd diverged.

It might be easiest to compare my "filter" and "master" branches (I just merged the former into the latter), if you're curious enough to want to see what changed.

**Comment by mjpost** [comment]
Should I close this PR? Seems we have diverged.

**Comment by shuoyangd** [comment]
Yeah I'm closing this now. You seem to have lots of stuff tailored to your specific needs in that branch -- which is great and I may still want to borrow things from you in the future. But my goal is to keep my master branch minimalistic and keep project-specific functionalities in separate branches, so rather than doing a pull request I'll just check your branch periodically, or we can chat if you have stuff you'd like me to know :)

**Pull request closed without merging**
